// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSCl6nZQluxfAC96PD1rBQvZ6X_vdU8Zg',
    appId: '1:308056930472:web:8a748fd5956192bad16a9d',
    messagingSenderId: '308056930472',
    projectId: 'temple-mng-system',
    authDomain: 'temple-mng-system.firebaseapp.com',
    storageBucket: 'temple-mng-system.appspot.com',
    measurementId: 'G-1RWPWJH009',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABve3aaehuon8wDgpBAq7hnNVm1jpwjRI',
    appId: '1:308056930472:android:fde332884c9bf61bd16a9d',
    messagingSenderId: '308056930472',
    projectId: 'temple-mng-system',
    storageBucket: 'temple-mng-system.appspot.com',
  );
}
