// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKwVsJrtmtRZ6t70Rih2iPDpHlFfhRMls',
    appId: '1:276632272722:web:5d34a9aa0e87fe8402448b',
    messagingSenderId: '276632272722',
    projectId: 'tms-sskv',
    authDomain: 'tms-sskv.firebaseapp.com',
    storageBucket: 'tms-sskv.appspot.com',
    measurementId: 'G-HJP1ZFEJ8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWNnQ7944oS7XqGQhy1qeQFOPouqlp6Kc',
    appId: '1:276632272722:android:dd9d414e6f6fce4702448b',
    messagingSenderId: '276632272722',
    projectId: 'tms-sskv',
    storageBucket: 'tms-sskv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZFHhOTWnIlhKCp5_T7IYPDM0lcOXDPJ8',
    appId: '1:276632272722:ios:2ec73264f16356f002448b',
    messagingSenderId: '276632272722',
    projectId: 'tms-sskv',
    storageBucket: 'tms-sskv.appspot.com',
    iosBundleId: 'com.example.tms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZFHhOTWnIlhKCp5_T7IYPDM0lcOXDPJ8',
    appId: '1:276632272722:ios:c1caffc8dd3ecb1002448b',
    messagingSenderId: '276632272722',
    projectId: 'tms-sskv',
    storageBucket: 'tms-sskv.appspot.com',
    iosBundleId: 'com.example.tms.RunnerTests',
  );
}
